---
controller_credentials:
  - name: "Ansible Galaxy"
    description: ""
    credential_type: "Ansible Galaxy/Automation Hub API Token"
    organization: "Recursive Workflows"
    inputs:
      url: https://galaxy.ansible.com/

...
