---
controller_hosts:
  - name: "localhost"
    description: ""
    inventory: "AWX-Inventory"
    variables:
      ansible_connection: local
      ansible_python_interpreter: !unsafe '{{ ansible_playbook_python }}'
...
